// <auto-generated />
using System;
using Fip.Strive.Harvester.Application.Infrastructure.Indexing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fip.Strive.Harvester.Application.Infrastructure.Indexing.Migrations
{
    [DbContext(typeof(IndexContext))]
    [Migration("20251207213401_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("harvester-indexer")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fip.Strive.Harvester.Application.Infrastructure.Indexing.Data.DataIndex", b =>
                {
                    b.Property<string>("Filepath")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDay")
                        .HasColumnType("boolean");

                    b.Property<string>("ParentFilepath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Filepath");

                    b.HasIndex("Hash");

                    b.HasIndex("IsDay");

                    b.HasIndex("ParentFilepath");

                    b.HasIndex("Source");

                    b.HasIndex("Timestamp");

                    b.ToTable("Data", "harvester-indexer");
                });

            modelBuilder.Entity("Fip.Strive.Harvester.Application.Infrastructure.Indexing.Data.ExtractIndex", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Hash");

                    b.HasIndex("Filepath");

                    b.HasIndex("Source");

                    b.HasIndex("Version");

                    b.ToTable("Extracts", "harvester-indexer");
                });

            modelBuilder.Entity("Fip.Strive.Harvester.Application.Infrastructure.Indexing.Data.FileInstance", b =>
                {
                    b.Property<string>("Filepath")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentFilepath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Filepath");

                    b.HasIndex("Hash");

                    b.HasIndex("ParentFilepath");

                    b.ToTable("Files", "harvester-indexer");
                });

            modelBuilder.Entity("Fip.Strive.Harvester.Application.Infrastructure.Indexing.Data.SourceIndex", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<string>("ClassifyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Hash");

                    b.HasIndex("ClassifyHash");

                    b.HasIndex("Filepath");

                    b.HasIndex("Source");

                    b.HasIndex("Version");

                    b.ToTable("Sources", "harvester-indexer");
                });

            modelBuilder.Entity("Fip.Strive.Harvester.Application.Infrastructure.Indexing.Data.ZipIndex", b =>
                {
                    b.Property<string>("Filepath")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Filepath");

                    b.HasIndex("Hash");

                    b.ToTable("Zips", "harvester-indexer");
                });

            modelBuilder.Entity("Fip.Strive.Harvester.Application.Infrastructure.Indexing.Data.FileInstance", b =>
                {
                    b.HasOne("Fip.Strive.Harvester.Application.Infrastructure.Indexing.Data.ZipIndex", "ParentZip")
                        .WithMany("Files")
                        .HasForeignKey("ParentFilepath")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentZip");
                });

            modelBuilder.Entity("Fip.Strive.Harvester.Application.Infrastructure.Indexing.Data.ZipIndex", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
