// <auto-generated />
using System;
using Fip.Strive.Harvester.Application.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fip.Strive.Harvester.Application.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(IndexContext))]
    [Migration("20251115124421_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("harvester-indexer")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fip.Strive.Harvester.Domain.Indexes.ZipIndex", b =>
                {
                    b.Property<string>("Filename")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Filename");

                    b.HasIndex("Hash");

                    b.ToTable("Zips", "harvester-indexer");
                });
#pragma warning restore 612, 618
        }
    }
}
