<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Fip.Strive.Tracking.Web</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Fip.Strive.Tracking.Application\Fip.Strive.Tracking.Application.csproj" />
  </ItemGroup>
</Project>
