// <auto-generated />
using System;
using Fip.Strive.Application.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fip.Strive.Application.Infrastructure.Migrations
{
    [DbContext(typeof(StriveContext))]
    partial class StriveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fip.Strive.Application.Features.Catalog.Models.CatalogEntry", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Hash");

                    b.HasIndex("FirstSeenUtc");

                    b.ToTable("catalog_entries", (string)null);
                });

            modelBuilder.Entity("Fip.Strive.Application.Features.Catalog.Models.ImportPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("NewEntryCount")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UploadedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveHash")
                        .IsUnique();

                    b.HasIndex("UploadedUtc");

                    b.ToTable("import_packages", (string)null);
                });

            modelBuilder.Entity("Fip.Strive.Application.Features.Catalog.Models.PackageFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("PathInArchive")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Hash");

                    b.HasIndex("PackageId", "PathInArchive")
                        .IsUnique();

                    b.ToTable("package_files", (string)null);
                });

            modelBuilder.Entity("Fip.Strive.Application.Features.Catalog.Models.PackageFile", b =>
                {
                    b.HasOne("Fip.Strive.Application.Features.Catalog.Models.CatalogEntry", "Entry")
                        .WithMany("Occurrences")
                        .HasForeignKey("Hash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fip.Strive.Application.Features.Catalog.Models.ImportPackage", "Package")
                        .WithMany("Files")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Fip.Strive.Application.Features.Catalog.Models.CatalogEntry", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("Fip.Strive.Application.Features.Catalog.Models.ImportPackage", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
