// <auto-generated />
using System;
using Fip.Strive.Indexing.Application.Infrastructure.Postgres.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fip.Strive.Indexing.Application.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(IndexPgContext))]
    partial class IndexPgContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ingestion-index")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fip.Strive.Indexing.Domain.DataIndex", b =>
                {
                    b.Property<string>("Filepath")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SignalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SignalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Filepath");

                    b.HasIndex("ParentId");

                    b.HasIndex("ReferenceId");

                    b.ToTable("Data", "ingestion-index");
                });

            modelBuilder.Entity("Fip.Strive.Indexing.Domain.FileHashed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Hash");

                    b.ToTable("FilesHashed", "ingestion-index");
                });

            modelBuilder.Entity("Fip.Strive.Indexing.Domain.FileIndex", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<int>("ClassfierVersion")
                        .HasColumnType("integer");

                    b.Property<int>("ClassificationResult")
                        .HasColumnType("integer");

                    b.Property<bool>("Classified")
                        .HasColumnType("boolean");

                    b.Property<string>("ClassifierHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExtractionMaxDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExtractionMinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Extractions")
                        .HasColumnType("integer");

                    b.Property<int>("ExtractorVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastClassificationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastExtractionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SignalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SignalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Hash");

                    b.HasIndex("ParentId");

                    b.HasIndex("ReferenceId");

                    b.ToTable("Files", "ingestion-index");
                });

            modelBuilder.Entity("Fip.Strive.Indexing.Domain.ZipHashed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Hash");

                    b.ToTable("ZipsHashed", "ingestion-index");
                });

            modelBuilder.Entity("Fip.Strive.Indexing.Domain.ZipIndex", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SignalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SignalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Hash");

                    b.HasIndex("ReferenceId");

                    b.ToTable("Zips", "ingestion-index");
                });

            modelBuilder.Entity("Fip.Strive.Ingestion.Domain.Models.DateEntry", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Date");

                    b.HasIndex("Day");

                    b.HasIndex("Month");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Year");

                    b.ToTable("Inventory", "ingestion-index");
                });

            modelBuilder.Entity("Fip.Strive.Indexing.Domain.DataIndex", b =>
                {
                    b.HasOne("Fip.Strive.Indexing.Domain.FileIndex", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Fip.Strive.Indexing.Domain.FileHashed", b =>
                {
                    b.HasOne("Fip.Strive.Indexing.Domain.FileIndex", "File")
                        .WithMany("Files")
                        .HasForeignKey("Hash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Fip.Strive.Indexing.Domain.FileIndex", b =>
                {
                    b.HasOne("Fip.Strive.Indexing.Domain.ZipIndex", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Fip.Strive.Indexing.Domain.ZipHashed", b =>
                {
                    b.HasOne("Fip.Strive.Indexing.Domain.ZipIndex", "Zip")
                        .WithMany("Files")
                        .HasForeignKey("Hash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zip");
                });

            modelBuilder.Entity("Fip.Strive.Indexing.Domain.FileIndex", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("Fip.Strive.Indexing.Domain.ZipIndex", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
